<div id='info'>
    <h1>Listato de Tutoriales (Practicas)</h1>
    <p>
    <ul>
        <li>
            <?php echo Html::link('variables', 'Pasando datos del controlador a la vista'); ?>
        </li>
        <li>
            <?php echo Html::link('modelos', 'Modelos (1)'); ?>
        </li>
        <li>
            <?php echo Html::link('modelos_2', 'Modelos (2)'); ?>
        </li>
    </ul>
</div>
