<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
        <title>KumbiaPHP web &amp; app Framework</title>
        <?php Tag::css('bienvenida') ?>
        <?php Tag::css('style') ?>
        <?php Tag::css('prettify') ?>
        <?php echo Html::includeCss() ?>
        <?php echo Tag::js('prettify') ?>
        <script type="text/javascript" >
            window.onload =function(){
                prettyPrint();
            };
        </script>
    </head>
    <body>
        <div id='content'>
            <div id='head'>
                <h1 id='logo'>KumbiaPHP</h1><div id='info-app'>web &amp; app Framework versión <?php echo kumbia_version() ?></div>

                <div class='alignright'>
                    <p id='config'>
                        <span class='app'><?php echo basename(dirname(APP_PATH)) ?></span>
                        <?php echo Html::link('pages/show/kumbia/status/', 'Config', 'title="Ver configuración de la aplicación"') ?>
                    </p>
                </div>
            </div>
                        <div style="margin-left: 100px">
                            <?php echo Html::link('', 'INICIO') ?> &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                            <?php echo Html::linkAction('', 'VOLVER') ?>
                    </div>

            <?php View::content(); ?>
            <?php View::partial('kumbia/footer') ?>
        </div>
    </body>
</html>
