<div id="info">
    <h1>Ejemplo de Uso del metodo find_first de active record</h1>
    <br/>
    <?php if ($resultado): ?>DATOS DEL PRIMER REGITRO EN LA TABLA MENU <small> $this->resultado = Load::model('menu')->find_first();</small>
    <br/>
        <ul>
            <li>ID: <?php eh($resultado->id)// eh() metodo que hace un echo y un htmlespecialchart de una cadena  ?></li>
            <li>NOMBRE: <?php eh($resultado->nombre)// tambien existe el metodo h() que hace el htmlespecialchart pero sin echo  ?></li>
            <li>URL: <?php eh($resultado->url) ?></li>
            <li>ESTADO: <?php eh($resultado->getEstado()) ?></li>
        </ul>
    <?php else: ?>
            No hay registros...!!!
    <?php endif; ?>
            <br/>
    <?php if ($usuario): ?>DATOS DEL PRIMER REGITRO EN LA TABLA USUARIOS <small>this->usuario =$usr->find_first(1);</small>
                <ul>
                    <li>ID: <?php eh($usuario->id)// eh() metodo que hace un echo y un htmlespecialchart de una cadena  ?></li>
                    <li>LOGIN: <?php eh($usuario->login)// tambien existe el metodo h() que hace el htmlespecialchart pero sin echo  ?></li>
                    <li>CLAVE: <?php eh($usuario->clave) ?></li>
                    <li>ESTADO: <?php eh($usuario->activo) ?></li>
                </ul>
    <?php else: ?>
                    No hay registros...!!!
    <?php endif; ?>
                    <br/>
    <?php if ($menu): ?>DATOS DEL ULTIMO REGITRO EN LA TABLA MENU <small>$this->menu = $menu->find_first('activo = 1','order: id DESC');</small>
    <ul>
        <li><?php echo $menu->inspect(); //el metodo inspect() de active record devuelve los nombres de campos y valores de un registro ?></li>
    </ul>
    <?php else: ?>
                            No hay registros...!!!
    <?php endif; ?>
    <hr/>
    <h3>URL de Ejemplo</h3>
    <pre class="prettyprint">
        http://localhost/tutoriales_kumbiaphp/modelos_2/find/
        partes de la url:
        dominio =  http://localhost/tutoriales_kumbiaphp/
        controlador = modelos_2
        accion = find
        parametros = no tiene</pre>
    <h3>Controlador</h3>
    <pre class="prettyprint">
class Modelos2Controller extends AppController {

    public function find_first(){
        /**
         * El metodo find_first devulve el primer registro encontrado en la
         * bd que cumpla con las condiciones pasadas como parametro,
         * generalmente se le pasa un numero entero que representa el id del
         * registro que se desea devolver, en el ejemplo no se le está pasando
         * ningun parametro, por lo tanto el metodo devolverá el primer
         * registro que consiga en la tabla.
         */
        $this->resultado = Load::model('menu')->find_first();
        /**
         * Otra manera de llamar al metodo find_first().
         *
         * En este ejemplo si se pasa un parametro que es el id del
         * usuario que se quiere devolver.
         */
        Load::models('usuario');
        $usr = new Usuario();
        $this->usuario =$usr->find_first(1);

        /**
         * Ahora si le pasamos una condicion al metodo.
         * Devolverá el ultimo registro activo que encuentre en la bd
         */
        $menu = Load::model('menu');
        $this->menu = $menu->find_first('activo = 1','order: id DESC');

    }
}</pre>
    <h3>Modelo Menu</h3>
    <pre class="prettyprint">
class Menu extends ActiveRecord {

    public function getEstado() {
        return $this->activo ? 'Activo' : 'Inactivo';
    }
}</pre>
    <h3>Modelo Usuario</h3>
    <pre class="prettyprint">
class Usuario extends ActiveRecord {

}</pre>
    <h3>Vista</h3>
    <pre class="prettyprint">
    <?php eh('<h1>Ejemplo de Uso del metodo find_first de active record</h1>
    <br/>
    <?php if ($resultado): ?>DATOS DEL PRIMER REGITRO EN LA TABLA MENU <small> $this->resultado = Load::model(\'menu\')->find_first();</small>
    <br/>
        <ul>
            <li>ID: <?php eh($resultado->id)// eh() metodo que hace un echo y un htmlespecialchart de una cadena  ?></li>
            <li>NOMBRE: <?php eh($resultado->nombre)// tambien existe el metodo h() que hace el htmlespecialchart pero sin echo  ?></li>
            <li>URL: <?php eh($resultado->url) ?></li>
            <li>ESTADO: <?php eh($resultado->getEstado()) ?></li>
        </ul>
    <?php else: ?>
            No hay registros...!!!
    <?php endif; ?>
            <br/>
    <?php if ($usuario): ?>DATOS DEL PRIMER REGITRO EN LA TABLA USUARIOS <small>this->usuario =$usr->find_first(1);</small>
                <ul>
                    <li>ID: <?php eh($usuario->id)// eh() metodo que hace un echo y un htmlespecialchart de una cadena  ?></li>
                    <li>LOGIN: <?php eh($usuario->login)// tambien existe el metodo h() que hace el htmlespecialchart pero sin echo  ?></li>
                    <li>CLAVE: <?php eh($usuario->clave) ?></li>
                    <li>ESTADO: <?php eh($usuario->activo) ?></li>
                </ul>
    <?php else: ?>
                    No hay registros...!!!
    <?php endif; ?>
                    <br/>
    <?php if ($menu): ?>DATOS DEL ULTIMO REGITRO EN LA TABLA MENU <small>$this->menu = $menu->find_first(\'activo = 1\',\'order: id DESC\');</small>
    <ul>
        <li><?php echo $menu->inspect(); //el metodo inspect() de active record devuelve los nombres de campos y valores de un registro ?></li>
    </ul>
    <?php else: ?>
                            No hay registros...!!!
    <?php endif; ?>'); ?>
    </pre>
</div>