<div id="info">
    <h1>Ejemplo de Validaciones de Datos en los Modelos</h1>
    <?php View::content(); ?>
    <?php echo Form::open(); ?>
    <dl>
        <dt>Nombre del Menú *</dt>
        <dd><?php echo Form::text('array_formulario.nombre'); ?></dd>
        <dt>URL del Menú *</dt>
        <dd><?php echo Form::text('array_formulario.url'); ?></dd>
        <dt>&nbsp;</dt>
        <dd><?php echo Form::submit('Enviar Formulario'); ?></dd>
    </dl>
    <?php echo Form::close(); ?>
</div>
