<div id="info">
    <h1>Ejemplo de Validaciones de Datos y uso de Callbacks en los Modelos</h1>
    <?php View::content(); ?>
    <?php echo Form::open(); ?>
    <dl>
        <dt>Login *</dt>
        <dd><?php echo Form::text('form.login'); ?></dd>
        <dt>Clave * (entre 3 y 10 caracteres)</dt>
        <dd><?php echo Form::pass('form.clave'); ?></dd>
        <dt>Repetir Clave *</dt>
        <dd><?php echo Form::pass('form.clave2'); ?></dd>
        <dt>&nbsp;</dt>
        <dd><?php echo Form::submit('Enviar Formulario'); ?></dd>
    </dl>
    <?php echo Form::close(); ?>
    <hr/>
    <h3>URL de Ejemplo</h3>
    <pre class="prettyprint">
        http://localhost/tutoriales_kumbiaphp/modelos/validaciones_2_callback/
        partes de la url:
        dominio =  http://localhost/tutoriales_kumbiaphp/
        controlador = modelos
        accion = validaciones_2_callback
        parametros = no tiene</pre>
    <h3>Controlador</h3>
    <pre class="prettyprint">
//con este metodo de la clase model podemos cargar varios modelos para
//usarlos en el controlador
Load::models('menu','usuario');

class ModelosController extends AppController {

    public function validaciones_2_callback(){
        if ( Input::hasPost('form') ){
            $model = new Usuario(Input::post('form'));

            if ( $model->save() ){
                Input::delete('form');
            }else{
                Flash::error('No se Han podido Guardar los datos...!!!');
            }
        }
    }
}</pre>
    <h3>Modelo</h3>
    <pre class="prettyprint">
class Usuario extends ActiveRecord {

    protected function initialize() {
        $this->validates_presence_of('login', 'message: Debe Especificar un Login');
        $this->validates_presence_of('clave', 'message: Debe Escribir una clave');
        $this->validates_presence_of('clave2', 'message: Debe Repetir la clave');
        $this->validates_length_of('clave', 10, 3);
        $this->validates_uniqueness_of('login','message: Este Login ya esta siendo usado en el Sistema');
    }

    protected function claves_iguales($clave1, $clave2) {
        return $clave1 === $clave2;
    }

    protected function before_validation_on_create() {
        if (!$this->claves_iguales($this->clave, $this->clave2)) {
            Flash::error('Las Claves no Coinciden');
            return 'cancel'; //retornamos el string 'cancel' para que
            //active record no continue con el guardado.
        }
    }

    protected function before_create() {
        //ejemplo de uso de los callback en active record
        //podemos obtener los valores de los campos simplemente
        //accediendo a los mismos como atributos del modelo (clase).
        $this->clave = md5($this->clave);
        $this->activo = '1';
    }

    protected function after_create() {
        Flash::valid("El Usuario $this->login fué creado exitosamente...!!!");
    }
}</pre>
    <h3>Vista</h3>
    <pre class="prettyprint">
    <?php eh('<h1>Ejemplo de Validaciones de Datos y uso de Callbacks en los Modelos</h1>
    <?php View::content(); ?>
    <?php echo Form::open(); ?>
    <dl>
        <dt>Login *</dt>
        <dd><?php echo Form::text(\'form.login\'); ?></dd>
        <dt>Clave * (entre 3 y 10 caracteres)</dt>
        <dd><?php echo Form::pass(\'form.clave\'); ?></dd>
        <dt>Repetir Clave *</dt>
        <dd><?php echo Form::pass(\'form.clave2\'); ?></dd>
        <dt>&nbsp;</dt>
        <dd><?php echo Form::submit(\'Enviar Formulario\'); ?></dd>
    </dl>
    <?php echo Form::close(); ?>'); ?>
    </pre>
</div>
