<div id="info">
    <h1>Ejemplo de Validaciones de Datos en los Modelos</h1>
    <?php View::content(); ?>
    <?php echo Form::open(); ?>
    <dl>
        <dt>Nombre del Menú *</dt>
        <dd><?php echo Form::text('array_formulario.nombre'); ?></dd>
        <dt>URL del Menú *</dt>
        <dd><?php echo Form::text('array_formulario.url'); ?></dd>
        <dt>&nbsp;</dt>
        <dd><?php echo Form::submit('Enviar Formulario'); ?></dd>
    </dl>
    <?php echo Form::close(); ?>
    <hr/>
    <h3>URL de Ejemplo</h3>
    <pre class="prettyprint">
        http://localhost/tutoriales_kumbiaphp/modelos/validaciones_1/
        partes de la url:
        dominio =  http://localhost/tutoriales_kumbiaphp/
        controlador = modelos
        accion = validaciones_1
        parametros = no tiene</pre>
    <h3>Controlador</h3>
    <pre class="prettyprint">
//con este metodo de la clase model podemos cargar varios modelos para
//usarlos en el controlador
Load::models('menu','usuario');

class ModelosController extends AppController {

    public function validaciones_1(){
        if ( Input::hasPost('array_formulario') ){
            $model = new Menu(Input::post('array_formulario'));

            if ( $model->save() ){
                Flash::valid("El menu $model->nombre fué creado exitosamente...!!!");
                Input::delete('array_formulario');
            }else{
                Flash::error('No se Han podido Guardar los datos...!!!');
            }
        }
    }
}</pre>
    <h3>Modelo</h3>
    <pre class="prettyprint">
class Menu extends ActiveRecord {

    //metodo equivalente al constructor de la clase, es llamado en el
    //constructor padre
    public function initialize() {
        //por defecto el active record va a validar los campos que sean
        //NOT NULL en la tabla de la base de datos
        //En este caso la tabla menu tiene 2 campos not null:
        //los campos nombre,url (la clave primaria no se toma en cuenta)
        //sin embargo para efectos del ejemplo se hará uso de las validaciones
        //de active record para cambiar los mensajes a mostrar en caso de
        //error en la validacion de los campos.
        $this->validates_presence_of('nombre', 'message: Debe Escribir un Nombre para el Menú...!!!');
        $this->validates_presence_of('url', 'message: Debe Escribir una URL para el Menú...!!!');
        $this->validates_uniqueness_of('nombre', 'message: Este nombre de menú ya existe en el sistema');
    }
}</pre>
    <h3>Vista</h3>
    <pre class="prettyprint">
    <?php eh('<h1>Ejemplo de Validaciones de Datos en los Modelos</h1>
    <?php View::content(); ?>
    <?php echo Form::open(); ?>
    <dl>
        <dt>Nombre del Menú *</dt>
        <dd><?php echo Form::text(\'array_formulario.nombre\'); ?></dd>
        <dt>URL del Menú *</dt>
        <dd><?php echo Form::text(\'array_formulario.url\'); ?></dd>
        <dt>&nbsp;</dt>
        <dd><?php echo Form::submit(\'Enviar Formulario\'); ?></dd>
    </dl>
    <?php echo Form::close(); ?>'); ?>
    </pre>
</div>
