<div id='info'>
    <h1>Listato de Tutoriales (Variables)</h1>
    <p>
    <ul>
        <li>
            <?php echo Html::link('variables/pasar_variable_vista', 'Pasando datos del controlador a la vista'); ?>
        </li>
        <li>
            <?php echo Html::link('variables/pasar_parametros_vista/manuel+aguirre/23',
                    'Pasando Parametros de una acción del controlador a la vista'); ?>
        </li>
        <li>
            <?php echo Html::link('variables/cargando_datos_form_1',
                    'Cargando datos en un formulario desde el controlador (1)'); ?>
        </li>
        <li>
            <?php echo Html::link('variables/cargando_datos_form_2',
                    'Cargando datos en un formulario desde el controlador (2)'); ?>
        </li>
        <li>
            <?php echo Html::link('variables/cargando_datos_form_3',
                    'Cargando datos en un formulario desde el controlador (3)'); ?>
        </li>
    </ul>
</p>
</div>
