<div id="info">
    
<ul>
<h2>Pasando Datos del Controlador a la Vista</h2>
<br/>
<p>
    <li>La variable <b>nombre</b> tiene el valor: <?php echo $nombre ?></li>
    <li>La variable <b>fecha_de_hoy</b> tiene el valor: <?php echo $fecha_de_hoy ?></li>
    <li>La variable <b>variable_local</b> no existe aquí.</li>
</ul>
</p>
<br/>
<br/>
<p>
    En este ejemplo la variable $nombre es la variable que hemos pasado como<br/>
    atributo del controlador ( $this->nombre ).<br/>
    Los mismo para la variable Edad.
</p>
</div>
